# Generated by Django 2.0.2 on 2018-06-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
