# Generated by Django 2.2.5 on 2019-09-19 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190915_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, upload_to='profile_image')),
                ('user_type', models.CharField(blank=True, choices=[('FARMER', 'FARMER'), ('WHOLESELLER', 'WHOLESELLER')], default='FARMER', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
