# Generated by Django 2.2.5 on 2019-09-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_our_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('FARMER', 'FARMER'), ('WHOLESELLER', 'WHOLESELLER')], default='FARMER', max_length=20),
        ),
    ]
