# Generated by Django 2.2.5 on 2019-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('crop_description', models.CharField(max_length=300)),
                ('crop_image', models.ImageField(blank=True, upload_to='crop_image')),
            ],
        ),
        migrations.CreateModel(
            name='harvest_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=50, unique=True)),
                ('crop_type_description', models.CharField(max_length=300)),
                ('crop_type_image', models.ImageField(blank=True, upload_to='crop_type_image')),
            ],
        ),
        migrations.CreateModel(
            name='sell_crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='In tonnes')),
                ('farm_image', models.ImageField(blank=True, upload_to='farm_image')),
                ('harvest_variety', models.CharField(max_length=100)),
                ('h_description', models.CharField(max_length=500)),
                ('quality', models.CharField(blank=True, choices=[('P', 'PREMIUM'), ('VG', 'VERY GOOD'), ('G', 'GOOD'), ('JR', 'JUST RIGHT')], default='P', help_text='Quality of crop', max_length=2)),
                ('crops', models.ForeignKey(on_delete='CASCADE', related_name='sell_cropss', to='sale_crop_proceeds.crops')),
            ],
        ),
        migrations.AddField(
            model_name='crops',
            name='crop_harvest_type',
            field=models.ForeignKey(on_delete='CASCADE', related_name='crops', to='sale_crop_proceeds.harvest_type'),
        ),
    ]
