# Generated by Django 2.2.5 on 2019-09-15 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_crop_proceeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell_harvested_crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='In tonnes')),
                ('farm_image', models.ImageField(blank=True, upload_to='farm_image')),
                ('harvest_variety', models.CharField(max_length=100)),
                ('h_description', models.CharField(max_length=500)),
                ('quality', models.CharField(blank=True, choices=[('P', 'PREMIUM'), ('VG', 'VERY GOOD'), ('G', 'GOOD'), ('JR', 'JUST RIGHT')], default='P', help_text='Quality of crop', max_length=2)),
                ('crops', models.ForeignKey(on_delete='CASCADE', related_name='sellCrops', to='sale_crop_proceeds.crops')),
                ('sold_by', models.ForeignKey(on_delete='CASCADE', related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
