# Generated by Django 2.2.5 on 2019-09-19 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_crop_proceeds', '0002_sell_harvested_crops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='In tonnes')),
                ('buy_crops', models.ForeignKey(on_delete='CASCADE', related_name='buycrops', to='sale_crop_proceeds.crops')),
                ('buyer', models.ForeignKey(on_delete='CASCADE', related_name='mybuyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='sell_crops',
        ),
    ]
