# Generated by Django 2.2.5 on 2019-09-19 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_crop_proceeds', '0003_auto_20190919_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_harvested_Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='In tonnes')),
                ('buy_crops', models.ForeignKey(on_delete='CASCADE', related_name='buy_harvested_Crops', to='sale_crop_proceeds.sell_harvested_crops')),
                ('buyer', models.ForeignKey(on_delete='CASCADE', related_name='mybuyers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
