# Generated by Django 2.2.5 on 2019-09-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale_crop_proceeds', '0004_buy_harvested_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy_Crop',
        ),
    ]
